# Generated by Django 4.2.2 on 2023-06-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='breve',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_diploma',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Graduado em:'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_matricula',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Matriculado em:'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome_curso',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
