# Generated by Django 4.2.2 on 2023-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_documento_breve_alter_documento_data_diploma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='sobrenome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
    ]
