# Generated by Django 4.2.2 on 2023-06-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_socio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='sobrenome',
        ),
    ]
