# Generated by Django 4.2.2 on 2023-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_socio_nome_remove_socio_sobrenome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
