# Generated by Django 4.2.1 on 2023-06-16 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_alter_socio_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socio', to=settings.AUTH_USER_MODEL),
        ),
    ]
