# Generated by Django 4.2.1 on 2023-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breve', models.CharField(default='', max_length=20, null=True)),
                ('nome_curso', models.TextField(default='', max_length=200, null=True)),
                ('data_diploma', models.DateTimeField(default=None, null=True, verbose_name='Graduado em:')),
                ('data_matricula', models.DateTimeField(default=None, null=True, verbose_name='Matriculado em:')),
                ('notas', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(max_length=3)),
                ('endereço', models.CharField(max_length=400)),
            ],
        ),
    ]
