# Generated by Django 4.2.1 on 2023-06-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VooAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_chegada', models.DateTimeField()),
                ('hora_saida', models.DateTimeField()),
                ('parecer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VooPiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_chegada', models.DateTimeField()),
                ('hora_saida', models.DateTimeField()),
            ],
        ),
    ]
