# Generated by Django 4.2.2 on 2023-06-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_socio_idade'),
        ('voos', '0003_acompanhamentovoo_voo_delete_vooaluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='data',
        ),
        migrations.AlterField(
            model_name='acompanhamentovoo',
            name='parecer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_chegada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voo',
            name='hora_saida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voos', to='usuarios.socio'),
        ),
    ]
