# Generated by Django 4.2.1 on 2023-06-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0004_remove_voo_data_alter_acompanhamentovoo_parecer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentovoo',
            name='voo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='voos.voo'),
        ),
    ]
