# Generated by Django 4.2.1 on 2023-06-21 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_socio_user'),
        ('voos', '0005_alter_acompanhamentovoo_voo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='instrutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usuarios.socio'),
        ),
        migrations.AddField(
            model_name='voo',
            name='nota',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='voo',
            name='parecer',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='AcompanhamentoVoo',
        ),
    ]
