# Generated by Django 4.2.1 on 2023-06-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_socio_user'),
        ('voos', '0006_voo_instrutor_voo_nota_voo_parecer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.socio'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='nota',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voo',
            name='parecer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
