# Generated by Django 4.2.1 on 2023-06-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0010_alter_voo_instrutor_alter_voo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='parecer',
            field=models.TextField(default='', null=True),
        ),
    ]
