# Generated by Django 4.2.1 on 2023-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0011_alter_voo_parecer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='parecer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
