# Generated by Django 4.2.1 on 2023-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_socio_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='breve',
            field=models.CharField(default=None, max_length=5, null=True, unique=True),
        ),
    ]
